import 'package:dartz/dartz.dart';
import 'package:progress_group/features/contact/domain/entities/activity/activity_prospect_status.dart';
import 'package:progress_group/features/contact/domain/entities/pameran/pameran_aktif_entity.dart';
import 'package:progress_group/features/contact/domain/entities/activity/create_activity_visit_params.dart';
import 'package:progress_group/features/contact/domain/entities/activity/whatsapp_activity_entity.dart';
import 'package:progress_group/features/contact/domain/entities/attachment/attachment_entity.dart';
import 'package:progress_group/features/contact/domain/entities/attachment/upload_attachment_params.dart';
import 'package:progress_group/features/contact/domain/entities/info_source/info_source.dart';
import 'package:progress_group/features/contact/domain/entities/lost_reason/lost_reason_entity.dart';
import 'package:progress_group/features/contact/domain/entities/property/property_unit_entity.dart';
import 'package:progress_group/features/contact/data/models/unit/unit_hierarchy_model.dart';
import '../entities/activity/activity_entity.dart';
import '../entities/contact/contact_entity.dart';
import '../entities/contact/contact_response.dart';
import '../entities/activity/create_activity_params.dart';
import '../entities/prospect/prospect_status.dart';
import '../entities/contact/create_contact_params.dart';
import '../entities/contact/contact_property.dart';
import '../entities/attachment/attachment_type.dart';

abstract class ContactRepository {
  Future<Either<String, List<AttachmentType>>> getAttachmentTypes();
  Future<Either<String, ContactResponse>> getContacts({int page = 1, int perPage = 10, String? search, String? startDate, String? endDate, List<int>? ownerIds, List<int>? statusProspectIds, List<int>? salesChannelIds, List<int>? salesChannelDetailIds, List<int>? salesTeamIds, List<int>? salesExecutiveIds, List<int>? salesSupervisorIds, List<int>? salesManagerIds, List<int>? salesGeneralManagerIds, String? apptStartDate, String? apptEndDate, String? visitStartDate, String? visitEndDate, String? reserveStartDate, String? reserveEndDate, String? spStartDate, String? spEndDate, String? lostStartDate, String? lostEndDate, String? lastProject, String? sort});
  Future<Either<String, List<ContactEntity>>> getAllContactsForDuplicateCheck();
  Future<Either<String, ContactEntity>> getContactDetail(int id);
  Future<Either<String, ContactEntity?>> checkDuplicateContact({required int ownerId, required String phone});
    Future<Either<String, List<InfoSource>>> getInfoSources({int? type, int? userId, String? salesChannel, bool all = false});
  Future<Either<String, List<InfoSource>>> getSalesChannelDetails();
  Future<Either<String, List<ProspectStatusEntity>>> getProspectStatuses({String? type});
  Future<Either<String, List<ProspectStatusEntity>>> getContactFormProspectStatuses({int? contactId});
  Future<Either<String, List<LostReasonEntity>>> getLostReasons();
  Future<Either<String, List<ContactPropertyGroup>>> getContactProperties();
  Future<Either<String, ContactEntity>> updateContact(int id, CreateContactParams params);
  Future<Either<String, ContactEntity>> createContact(CreateContactParams params);
  Future<Either<String, void>> deleteContact(int id);
  Future<Either<String, List<ActivityEntity>>> getActivities({int? contactId, int? dealId, String? activityType, String? followUpStartDate, String? followUpEndDate, int page = 1,});
  Future<Either<String, void>> createActivityVisit(CreateVisitParams params);
  Future<Either<String, void>> createActivity(CreateActivityParams params);
  Future<Either<String, void>> postStatusFollow(List<int> activityIds);
  Future<Either<String, List<ActivityProspectStatusEntity>>> getActivityProspectStatus(int contactId);
  Future<Either<String, List<WhatsappUnreadSummaryEntity>>> getWhatsappUnreadSummary(int contactId);
  Future<Either<String, void>> uploadAttachment(UploadAttachmentParams params);
  Future<Either<String, List<ContactAttachment>>> getAttachments({  required int contactId,  int? dealId,});
  Future<Either<String, void>> deleteAttachment({required int contactId,required int attachmentId,});
  Future<Either<String, void>> updateAttachment({  required int contactId,  required int attachmentId,  required UploadAttachmentParams params,});
  Future<Either<String, List<PropertyUnitCluster>>> getPropertyUnits({required int townshipId});
  Future<Either<String, List<PropertyUnitCluster>>> getPropertyCommercialUnits({required int townshipId});
  Future<Either<String, List<UnitCluster>>> getUnitHierarchy({required int townshipId, String? search});
  Future<Either<String, List<UnitLot>>> getUnitLots({required int productId, int? townshipId, int? companyId, String? search});
  Future<Either<String, List<PameranAktifEntity>>> getPameranAktif({String? lokasiPameran, int? userId, bool all = false});
  Future<Either<String, List<String>>> getProductTypes();
}
