// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Nilai diambil dari google-services.json (paradise-connect-mobile-6effd)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKkkCwhqqTeqHUQ8OFloW4e9gDg8WmrY',
    appId: '1:729428932735:android:8ec407c3ca726a7ea6274a',
    messagingSenderId: '729428932735',
    projectId: 'paradise-connect-mobile-6effd',
    storageBucket: 'paradise-connect-mobile-6effd.firebasestorage.app',
  );

  // iOS — sesuaikan dengan GoogleService-Info.plist jika ada
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARKkkCwhqqTeqHUQ8OFloW4e9gDg8WmrY',
    appId: '1:729428932735:ios:8ec407c3ca726a7ea6274a',
    messagingSenderId: '729428932735',
    projectId: 'paradise-connect-mobile-6effd',
    storageBucket: 'paradise-connect-mobile-6effd.firebasestorage.app',
    iosBundleId: 'com.example.progressGroup',
  );
}
